package com.jnzader.apigen.server.service.generator;

import static com.jnzader.apigen.server.service.generator.util.SampleDataGenerator.getSampleValue;
import static com.jnzader.apigen.server.service.generator.util.StringTransformationUtil.capitalize;
import static com.jnzader.apigen.server.service.generator.util.StringTransformationUtil.escapeJsonString;
import static com.jnzader.apigen.server.service.generator.util.StringTransformationUtil.toCamelCase;

import com.jnzader.apigen.codegen.model.SqlColumn;
import com.jnzader.apigen.codegen.model.SqlSchema;
import com.jnzader.apigen.codegen.model.SqlTable;
import com.jnzader.apigen.server.dto.GenerateRequest;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import org.springframework.stereotype.Component;

/** Generates API testing files (HTTP test files, Postman collections). */
@Component
public class ApiTestingGenerator {

    private static final String DEFAULT_BASE_URL = "http://localhost:8080/api/v1";

    /** Returns the default base URL for a given language. */
    public static String getBaseUrlForLanguage(String language) {
        if (language == null) {
            return DEFAULT_BASE_URL;
        }
        return switch (language.toLowerCase(java.util.Locale.ROOT)) {
            case "python" -> "http://localhost:8000/api/v1";
            case "php" -> "http://localhost:8000/api/v1";
            case "typescript" -> "http://localhost:3000/api/v1";
            case "csharp" -> "http://localhost:5000/api/v1";
            default -> DEFAULT_BASE_URL; // java, kotlin, go, rust
        };
    }

    private static final String POSTMAN_SCHEMA_URL =
            "https://schema.getpostman.com/json/collection/v2.1.0/collection.json";
    private static final String BASE_URL_VAR = "{{baseUrl}}/";
    private static final String CONTENT_TYPE_JSON = "Content-Type: application/json\n\n";
    private static final String ID_PATH = "/1";

    @SuppressWarnings("java:S1075") // Path segment for testing, not a full URI
    private static final String ID_PATH_NEWLINE = "/1\n";

    @SuppressWarnings("java:S1075") // Path segment for testing, not a full URI
    private static final String ID_PATH_DOUBLE_NEWLINE = "/1\n\n";

    private static final String JSON_FIELD_END = "\",\n";

    /**
     * Generates HTTP test file for all entities with all 12 CRUD endpoints.
     *
     * @param schema the SQL schema
     * @return the HTTP test file content
     */
    public String generateHttpTestFile(SqlSchema schema) {
        return generateHttpTestFile(schema, null);
    }

    /**
     * Generates HTTP test file for all entities with all 12 CRUD endpoints.
     *
     * @param schema the SQL schema
     * @param language the target language (for port selection)
     * @return the HTTP test file content
     */
    public String generateHttpTestFile(SqlSchema schema, String language) {
        String baseUrl = getBaseUrlForLanguage(language);
        StringBuilder sb = new StringBuilder();

        sb.append(
                        """
                        # =============================================================================
                        # API Test Collection - Generated by APiGen Studio
                        # =============================================================================
                        # Usage:
                        #   - VS Code: Install "REST Client" extension
                        #   - IntelliJ IDEA: Built-in HTTP Client support
                        #   - Run requests by clicking "Send Request" above each request
                        # =============================================================================

                        @baseUrl =\
                        """)
                .append(" ")
                .append(baseUrl)
                .append(
                        """

                        """);

        for (SqlTable table : schema.getEntityTables()) {
            String entityName = table.getEntityName();
            String moduleName = table.getModuleName();
            String endpoint = BASE_URL_VAR + moduleName;

            sb.append(
                    """

                    # =============================================================================
                    """);
            sb.append("# ")
                    .append(entityName.toUpperCase())
                    .append(" ENDPOINTS (")
                    .append(moduleName)
                    .append(")\n");
            sb.append(
                    """
                    # =============================================================================

                    """);

            // 1. GET / - List all with pagination
            sb.append("### 1. List all ").append(moduleName).append(" (paginated)\n");
            sb.append("GET ").append(endpoint).append("?page=0&size=10&sort=id,desc\n\n");

            // 2. GET / with filter
            sb.append("### 2. List ").append(moduleName).append(" with filter\n");
            sb.append("GET ").append(endpoint).append("?filter=id:gt:0\n\n");

            // 3. GET / with sparse fieldsets
            sb.append("### 3. List ").append(moduleName).append(" with sparse fieldsets\n");
            sb.append("GET ").append(endpoint).append("?fields=id");
            List<SqlColumn> businessCols = table.getBusinessColumns();
            if (!businessCols.isEmpty()) {
                sb.append(",").append(businessCols.get(0).getJavaFieldName());
            }
            sb.append("\n\n");

            // 4. HEAD / - Count
            sb.append("### 4. Count ").append(moduleName).append("\n");
            sb.append("HEAD ").append(endpoint).append("\n\n");

            // 5. GET /{id} - Get by ID
            sb.append("### 5. Get ").append(entityName.toLowerCase()).append(" by ID\n");
            sb.append("GET ").append(endpoint).append(ID_PATH_DOUBLE_NEWLINE);

            // 6. HEAD /{id} - Exists check
            sb.append("### 6. Check if ").append(entityName.toLowerCase()).append(" exists\n");
            sb.append("HEAD ").append(endpoint).append(ID_PATH_DOUBLE_NEWLINE);

            // 7. POST / - Create
            sb.append("### 7. Create new ").append(entityName.toLowerCase()).append("\n");
            sb.append("POST ").append(endpoint).append("\n");
            sb.append(CONTENT_TYPE_JSON);
            sb.append(generateSampleJson(table, false)).append("\n\n");

            // 8. PUT /{id} - Full update
            sb.append("### 8. Update ").append(entityName.toLowerCase()).append(" (full)\n");
            sb.append("PUT ").append(endpoint).append(ID_PATH_NEWLINE);
            sb.append(CONTENT_TYPE_JSON);
            sb.append(generateSampleJson(table, true)).append("\n\n");

            // 9. PATCH /{id} - Partial update
            sb.append("### 9. Update ").append(entityName.toLowerCase()).append(" (partial)\n");
            sb.append("PATCH ").append(endpoint).append(ID_PATH_NEWLINE);
            sb.append(CONTENT_TYPE_JSON);
            sb.append(generatePartialUpdateJson(table)).append("\n\n");

            // 10. DELETE /{id} - Soft delete
            sb.append("### 10. Soft delete ").append(entityName.toLowerCase()).append("\n");
            sb.append("DELETE ").append(endpoint).append(ID_PATH_DOUBLE_NEWLINE);

            // 11. POST /{id}/restore - Restore
            sb.append("### 11. Restore soft-deleted ")
                    .append(entityName.toLowerCase())
                    .append("\n");
            sb.append("POST ").append(endpoint).append(ID_PATH).append("/restore\n\n");

            // 12. DELETE /{id}?permanent=true - Permanent delete
            sb.append("### 12. Permanently delete ").append(entityName.toLowerCase()).append("\n");
            sb.append("DELETE ").append(endpoint).append(ID_PATH).append("?permanent=true\n\n");

            // Bonus: Cursor pagination
            sb.append("### BONUS: Cursor-based pagination\n");
            sb.append("GET ").append(endpoint).append("/cursor?size=10&sort=id&direction=DESC\n\n");
        }

        return sb.toString();
    }

    /**
     * Generates a Postman Collection v2.1 JSON for testing all API endpoints.
     *
     * @param schema the SQL schema
     * @param config the project configuration
     * @return the Postman collection JSON
     */
    public String generatePostmanCollection(
            SqlSchema schema, GenerateRequest.ProjectConfig config) {
        return generatePostmanCollection(schema, config, null);
    }

    /**
     * Generates a Postman Collection v2.1 JSON for testing all API endpoints.
     *
     * @param schema the SQL schema
     * @param config the project configuration
     * @param language the target language (for port selection)
     * @return the Postman collection JSON
     */
    public String generatePostmanCollection(
            SqlSchema schema, GenerateRequest.ProjectConfig config, String language) {
        String baseUrl = getBaseUrlForLanguage(language);
        String projectName = config.getName() != null ? config.getName() : "my-api";
        String collectionName = capitalize(projectName) + " API Collection";

        StringBuilder sb = new StringBuilder();
        sb.append("{\n");
        sb.append("  \"info\": {\n");
        sb.append("    \"name\": \"").append(collectionName).append(JSON_FIELD_END);
        sb.append(
                "    \"description\": \"API Collection generated by APiGen Studio. Import this file"
                        + " into Postman to test all endpoints.\",\n");
        sb.append("    \"schema\": \"").append(POSTMAN_SCHEMA_URL).append("\"\n");
        sb.append("  },\n");

        // Variables
        sb.append("  \"variable\": [\n");
        sb.append("    {\n");
        sb.append("      \"key\": \"baseUrl\",\n");
        sb.append("      \"value\": \"").append(baseUrl).append(JSON_FIELD_END);
        sb.append("      \"type\": \"string\"\n");
        sb.append("    }\n");
        sb.append("  ],\n");

        // Items (folders for each entity)
        sb.append("  \"item\": [\n");

        List<SqlTable> tables = schema.getEntityTables();
        for (int t = 0; t < tables.size(); t++) {
            SqlTable table = tables.get(t);
            String entityName = table.getEntityName();
            String moduleName = table.getModuleName();

            sb.append("    {\n");
            sb.append("      \"name\": \"").append(entityName).append(JSON_FIELD_END);
            sb.append("      \"item\": [\n");

            // Generate all requests for this entity
            List<String> requests = new ArrayList<>();

            // 1. GET / - List all
            requests.add(
                    generatePostmanRequest(
                            "List all " + moduleName,
                            "GET",
                            BASE_URL_VAR + moduleName + "?page=0&size=10&sort=id,desc",
                            null,
                            "Returns paginated list of " + moduleName));

            // 2. GET /{id} - Get by ID
            requests.add(
                    generatePostmanRequest(
                            "Get " + entityName.toLowerCase() + " by ID",
                            "GET",
                            BASE_URL_VAR + moduleName + ID_PATH,
                            null,
                            "Returns a single " + entityName.toLowerCase() + " by ID"));

            // 3. HEAD /{id} - Check exists
            requests.add(
                    generatePostmanRequest(
                            "Check if " + entityName.toLowerCase() + " exists",
                            "HEAD",
                            BASE_URL_VAR + moduleName + ID_PATH,
                            null,
                            "Returns 200 if exists, 404 if not"));

            // 4. HEAD / - Count
            requests.add(
                    generatePostmanRequest(
                            "Count " + moduleName,
                            "HEAD",
                            BASE_URL_VAR + moduleName,
                            null,
                            "Returns total count in X-Total-Count header"));

            // 5. POST / - Create
            requests.add(
                    generatePostmanRequest(
                            "Create new " + entityName.toLowerCase(),
                            "POST",
                            BASE_URL_VAR + moduleName,
                            generateSampleJsonCompact(table, false),
                            "Creates a new " + entityName.toLowerCase()));

            // 6. PUT /{id} - Full update
            requests.add(
                    generatePostmanRequest(
                            "Update " + entityName.toLowerCase() + " (full)",
                            "PUT",
                            BASE_URL_VAR + moduleName + ID_PATH,
                            generateSampleJsonCompact(table, true),
                            "Replaces all fields of the " + entityName.toLowerCase()));

            // 7. PATCH /{id} - Partial update
            requests.add(
                    generatePostmanRequest(
                            "Update " + entityName.toLowerCase() + " (partial)",
                            "PATCH",
                            BASE_URL_VAR + moduleName + ID_PATH,
                            generatePartialUpdateJsonCompact(table),
                            "Updates only specified fields"));

            // 8. DELETE /{id} - Soft delete
            requests.add(
                    generatePostmanRequest(
                            "Soft delete " + entityName.toLowerCase(),
                            "DELETE",
                            BASE_URL_VAR + moduleName + ID_PATH,
                            null,
                            "Marks as deleted (can be restored)"));

            // 9. POST /{id}/restore - Restore
            requests.add(
                    generatePostmanRequest(
                            "Restore " + entityName.toLowerCase(),
                            "POST",
                            BASE_URL_VAR + moduleName + ID_PATH + "/restore",
                            null,
                            "Restores a soft-deleted record"));

            // 10. DELETE /{id}?permanent=true - Hard delete
            requests.add(
                    generatePostmanRequest(
                            "Permanently delete " + entityName.toLowerCase(),
                            "DELETE",
                            BASE_URL_VAR + moduleName + ID_PATH + "?permanent=true",
                            null,
                            "Permanently removes the record (cannot be undone)"));

            // 11. GET with filter
            requests.add(
                    generatePostmanRequest(
                            "List " + moduleName + " with filter",
                            "GET",
                            BASE_URL_VAR + moduleName + "?filter=id:gt:0",
                            null,
                            "Filter using field:operator:value syntax"));

            // 12. GET cursor pagination
            requests.add(
                    generatePostmanRequest(
                            "Cursor pagination",
                            "GET",
                            BASE_URL_VAR + moduleName + "/cursor?size=10&sort=id&direction=DESC",
                            null,
                            "Efficient pagination for large datasets"));

            sb.append(String.join(",\n", requests));
            sb.append("\n      ]\n");
            sb.append("    }");

            if (t < tables.size() - 1) {
                sb.append(",");
            }
            sb.append("\n");
        }

        sb.append("  ]\n");
        sb.append("}\n");

        return sb.toString();
    }

    /** Generates a single Postman request item. */
    private String generatePostmanRequest(
            String name, String method, String url, String body, String description) {
        StringBuilder sb = new StringBuilder();
        sb.append("        {\n");
        sb.append("          \"name\": \"").append(name).append(JSON_FIELD_END);
        sb.append("          \"request\": {\n");
        sb.append("            \"method\": \"").append(method).append(JSON_FIELD_END);
        sb.append("            \"header\": [\n");
        if (body != null) {
            sb.append("              {\n");
            sb.append("                \"key\": \"Content-Type\",\n");
            sb.append("                \"value\": \"application/json\"\n");
            sb.append("              }\n");
        }
        sb.append("            ],\n");

        // URL
        sb.append("            \"url\": {\n");
        sb.append("              \"raw\": \"").append(url).append(JSON_FIELD_END);

        // Parse URL for host/path/query
        String urlPath = url.replace("{{baseUrl}}", "");
        String pathPart =
                urlPath.contains("?") ? urlPath.substring(0, urlPath.indexOf("?")) : urlPath;
        String queryPart =
                urlPath.contains("?") ? urlPath.substring(urlPath.indexOf("?") + 1) : null;

        sb.append("              \"host\": [\"{{baseUrl}}\"],\n");
        if (!pathPart.isEmpty()) {
            String[] pathSegments = pathPart.substring(1).split("/");
            sb.append("              \"path\": [");
            sb.append(
                    Arrays.stream(pathSegments)
                            .map(s -> "\"" + s + "\"")
                            .collect(Collectors.joining(", ")));
            sb.append("]");
        } else {
            sb.append("              \"path\": []");
        }

        if (queryPart != null) {
            sb.append(",\n              \"query\": [\n");
            String[] params = queryPart.split("&");
            for (int i = 0; i < params.length; i++) {
                String[] kv = params[i].split("=");
                sb.append("                {\n");
                sb.append("                  \"key\": \"").append(kv[0]).append(JSON_FIELD_END);
                sb.append("                  \"value\": \"")
                        .append(kv.length > 1 ? kv[1] : "")
                        .append("\"\n");
                sb.append("                }");
                if (i < params.length - 1) sb.append(",");
                sb.append("\n");
            }
            sb.append("              ]");
        }
        sb.append("\n            }");

        // Body
        if (body != null) {
            sb.append(",\n            \"body\": {\n");
            sb.append("              \"mode\": \"raw\",\n");
            sb.append("              \"raw\": ").append(escapeJsonString(body)).append(",\n");
            sb.append("              \"options\": {\n");
            sb.append("                \"raw\": {\n");
            sb.append("                  \"language\": \"json\"\n");
            sb.append("                }\n");
            sb.append("              }\n");
            sb.append("            }");
        }

        sb.append(",\n            \"description\": \"").append(description).append("\"\n");
        sb.append("          }\n");
        sb.append("        }");

        return sb.toString();
    }

    /** Generates sample JSON for creating/updating an entity (pretty format). */
    private String generateSampleJson(SqlTable table, boolean includeId) {
        StringBuilder json = new StringBuilder("{\n");
        List<String> fields = new ArrayList<>();

        if (includeId) {
            fields.add("  \"id\": 1");
        }

        for (SqlColumn col : table.getBusinessColumns()) {
            String fieldName = col.getJavaFieldName();
            String sampleValue = getSampleValue(col);
            fields.add("  \"" + fieldName + "\": " + sampleValue);
        }

        // Add FK references if any
        for (var fk : table.getForeignKeys()) {
            String fieldName = fk.getColumnName().replace("_id", "");
            fieldName = toCamelCase(fieldName) + "Id";
            fields.add("  \"" + fieldName + "\": 1");
        }

        json.append(String.join(",\n", fields));
        json.append("\n}");
        return json.toString();
    }

    /** Generates sample JSON for creating/updating an entity (compact format for Postman). */
    private String generateSampleJsonCompact(SqlTable table, boolean includeId) {
        StringBuilder json = new StringBuilder("{");
        List<String> fields = new ArrayList<>();

        if (includeId) {
            fields.add("\"id\": 1");
        }

        for (SqlColumn col : table.getBusinessColumns()) {
            String fieldName = col.getJavaFieldName();
            String sampleValue = getSampleValue(col);
            fields.add("\"" + fieldName + "\": " + sampleValue);
        }

        for (var fk : table.getForeignKeys()) {
            String fieldName = fk.getColumnName().replace("_id", "");
            fieldName = toCamelCase(fieldName) + "Id";
            fields.add("\"" + fieldName + "\": 1");
        }

        json.append(String.join(", ", fields));
        json.append("}");
        return json.toString();
    }

    /** Generates sample JSON for partial update (pretty format). */
    private String generatePartialUpdateJson(SqlTable table) {
        StringBuilder json = new StringBuilder("{\n");
        List<SqlColumn> cols = table.getBusinessColumns();

        if (!cols.isEmpty()) {
            SqlColumn firstCol = cols.get(0);
            json.append("  \"")
                    .append(firstCol.getJavaFieldName())
                    .append("\": ")
                    .append(getSampleValue(firstCol, "updated"));
        }

        json.append("\n}");
        return json.toString();
    }

    /** Generates sample JSON for partial update (compact format for Postman). */
    private String generatePartialUpdateJsonCompact(SqlTable table) {
        StringBuilder json = new StringBuilder("{");
        List<SqlColumn> cols = table.getBusinessColumns();

        if (!cols.isEmpty()) {
            SqlColumn firstCol = cols.get(0);
            json.append("\"")
                    .append(firstCol.getJavaFieldName())
                    .append("\": ")
                    .append(getSampleValue(firstCol, "updated"));
        }

        json.append("}");
        return json.toString();
    }
}
