package com.jnzader.apigen.codegen.generator.dx;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Generator for enhanced docker-compose.yml for development.
 *
 * <p>Creates a docker-compose.yml with:
 *
 * <ul>
 *   <li>Health checks for all services
 *   <li>Named volumes for data persistence
 *   <li>Service profiles for optional components (cache, mail, admin, observability)
 *   <li>Development-friendly configuration
 * </ul>
 */
public class DevComposeGenerator {

    private final String projectName;
    private final String dbUser;
    private final String dbPassword;
    private final String dbName;

    public DevComposeGenerator(
            String projectName, String dbUser, String dbPassword, String dbName) {
        this.projectName = projectName;
        this.dbUser = dbUser != null ? dbUser : "app";
        this.dbPassword = dbPassword != null ? dbPassword : "secret";
        this.dbName = dbName != null ? dbName : "appdb";
    }

    /**
     * Generates enhanced docker-compose.yml content.
     *
     * @param language the target language/framework
     * @return map with file path as key and content as value
     */
    public Map<String, String> generate(DxLanguage language) {
        Map<String, String> files = new LinkedHashMap<>();
        files.put("docker-compose.yml", generateCompose(language));
        files.put(".env.example", generateEnvExample());
        return files;
    }

    private String generateCompose(DxLanguage language) {
        String appService = generateAppService(language);

        return """
                # docker-compose.yml - Generated by APiGen
                # Enhanced development configuration with profiles
                #
                # Usage:
                #   docker compose up -d                    # Start core services (postgres)
                #   docker compose --profile app up -d     # Start with application
                #   docker compose --profile cache up -d   # Start with Redis
                #   docker compose --profile mail up -d    # Start with MailHog
                #   docker compose --profile admin up -d   # Start with pgAdmin
                #   docker compose --profile observability up -d  # Start with Prometheus/Grafana

                services:
                  # ===========================================
                  # Database
                  # ===========================================
                  postgres:
                    image: postgres:16-alpine
                    container_name: %s-postgres
                    environment:
                      POSTGRES_USER: ${DB_USER:-%s}
                      POSTGRES_PASSWORD: ${DB_PASS:-%s}
                      POSTGRES_DB: ${DB_NAME:-%s}
                    ports:
                      - "${DB_PORT:-5432}:5432"
                    volumes:
                      - postgres-data:/var/lib/postgresql/data
                    healthcheck:
                      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-%s} -d ${DB_NAME:-%s}"]
                      interval: 5s
                      timeout: 5s
                      retries: 10
                      start_period: 10s
                    restart: unless-stopped

                %s
                  # ===========================================
                  # Cache (optional)
                  # ===========================================
                  redis:
                    image: redis:7-alpine
                    container_name: %s-redis
                    ports:
                      - "${REDIS_PORT:-6379}:6379"
                    volumes:
                      - redis-data:/data
                    healthcheck:
                      test: ["CMD", "redis-cli", "ping"]
                      interval: 5s
                      timeout: 3s
                      retries: 5
                    restart: unless-stopped
                    profiles:
                      - cache

                  # ===========================================
                  # Email Testing
                  # ===========================================
                  mailhog:
                    image: mailhog/mailhog:latest
                    container_name: %s-mailhog
                    ports:
                      - "${MAILHOG_SMTP:-1025}:1025"
                      - "${MAILHOG_UI:-8025}:8025"
                    restart: unless-stopped
                    profiles:
                      - mail

                  # ===========================================
                  # Database Admin
                  # ===========================================
                  pgadmin:
                    image: dpage/pgadmin4:latest
                    container_name: %s-pgadmin
                    environment:
                      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@local.dev}
                      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
                      PGADMIN_CONFIG_SERVER_MODE: "False"
                    ports:
                      - "${PGADMIN_PORT:-5050}:80"
                    volumes:
                      - pgadmin-data:/var/lib/pgadmin
                    depends_on:
                      postgres:
                        condition: service_healthy
                    restart: unless-stopped
                    profiles:
                      - admin

                  # ===========================================
                  # Observability
                  # ===========================================
                  prometheus:
                    image: prom/prometheus:latest
                    container_name: %s-prometheus
                    ports:
                      - "${PROMETHEUS_PORT:-9090}:9090"
                    volumes:
                      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
                      - prometheus-data:/prometheus
                    command:
                      - '--config.file=/etc/prometheus/prometheus.yml'
                      - '--storage.tsdb.path=/prometheus'
                      - '--web.enable-lifecycle'
                    restart: unless-stopped
                    profiles:
                      - observability

                  grafana:
                    image: grafana/grafana:latest
                    container_name: %s-grafana
                    environment:
                      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
                      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
                      GF_USERS_ALLOW_SIGN_UP: "false"
                    ports:
                      - "${GRAFANA_PORT:-3000}:3000"
                    volumes:
                      - grafana-data:/var/lib/grafana
                      - ./deploy/grafana/provisioning:/etc/grafana/provisioning:ro
                    depends_on:
                      - prometheus
                    restart: unless-stopped
                    profiles:
                      - observability

                volumes:
                  postgres-data:
                    name: %s-postgres-data
                  redis-data:
                    name: %s-redis-data
                  pgadmin-data:
                    name: %s-pgadmin-data
                  prometheus-data:
                    name: %s-prometheus-data
                  grafana-data:
                    name: %s-grafana-data

                networks:
                  default:
                    name: %s-network
                """
                .formatted(
                        projectName,
                        dbUser,
                        dbPassword,
                        dbName,
                        dbUser,
                        dbName,
                        appService,
                        projectName,
                        projectName,
                        projectName,
                        projectName,
                        projectName,
                        projectName,
                        projectName,
                        projectName,
                        projectName,
                        projectName,
                        projectName);
    }

    private String generateAppService(DxLanguage language) {
        String buildConfig = getBuildConfig(language);
        String envVars = getEnvVars(language);

        return """
                  # ===========================================
                  # Application
                  # ===========================================
                  app:
                    build:
                      context: .
                      dockerfile: Dockerfile
                %s
                    container_name: %s-app
                    ports:
                      - "${APP_PORT:-8080}:8080"
                %s
                    depends_on:
                      postgres:
                        condition: service_healthy
                    restart: unless-stopped
                    profiles:
                      - app

                """
                .formatted(buildConfig, projectName, envVars);
    }

    private String getBuildConfig(DxLanguage language) {
        return switch (language) {
            case JAVA_SPRING, KOTLIN_SPRING -> """
                          target: development
                    """;
            case CSHARP_ASPNET -> """
                          target: development
                    """;
            default -> "";
        };
    }

    private String getEnvVars(DxLanguage language) {
        return switch (language) {
            case JAVA_SPRING, KOTLIN_SPRING -> """
                        environment:
                          SPRING_PROFILES_ACTIVE: dev
                          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME:-%s}
                          SPRING_DATASOURCE_USERNAME: ${DB_USER:-%s}
                          SPRING_DATASOURCE_PASSWORD: ${DB_PASS:-%s}
                    """
                    .formatted(dbName, dbUser, dbPassword);
            case CSHARP_ASPNET -> """
                        environment:
                          ASPNETCORE_ENVIRONMENT: Development
                          ConnectionStrings__DefaultConnection: Host=postgres;Database=${DB_NAME:-%s};Username=${DB_USER:-%s};Password=${DB_PASS:-%s}
                    """
                    .formatted(dbName, dbUser, dbPassword);
            case PYTHON_FASTAPI -> """
                        environment:
                          DATABASE_URL: postgresql://${DB_USER:-%s}:${DB_PASS:-%s}@postgres:5432/${DB_NAME:-%s}
                          ENVIRONMENT: development
                    """
                    .formatted(dbUser, dbPassword, dbName);
            case TYPESCRIPT_NESTJS -> """
                        environment:
                          NODE_ENV: development
                          DATABASE_URL: postgresql://${DB_USER:-%s}:${DB_PASS:-%s}@postgres:5432/${DB_NAME:-%s}
                    """
                    .formatted(dbUser, dbPassword, dbName);
            case PHP_LARAVEL -> """
                        environment:
                          APP_ENV: local
                          DB_CONNECTION: pgsql
                          DB_HOST: postgres
                          DB_PORT: 5432
                          DB_DATABASE: ${DB_NAME:-%s}
                          DB_USERNAME: ${DB_USER:-%s}
                          DB_PASSWORD: ${DB_PASS:-%s}
                    """
                    .formatted(dbName, dbUser, dbPassword);
            case GO_GIN, GO_CHI -> """
                        environment:
                          DATABASE_URL: postgres://${DB_USER:-%s}:${DB_PASS:-%s}@postgres:5432/${DB_NAME:-%s}?sslmode=disable
                          GIN_MODE: debug
                    """
                    .formatted(dbUser, dbPassword, dbName);
            case RUST_AXUM -> """
                        environment:
                          DATABASE_URL: postgres://${DB_USER:-%s}:${DB_PASS:-%s}@postgres:5432/${DB_NAME:-%s}
                          RUST_LOG: debug
                    """
                    .formatted(dbUser, dbPassword, dbName);
        };
    }

    private String generateEnvExample() {
        return """
                # .env.example - Generated by APiGen
                # Copy to .env and customize for your environment

                # ===========================================
                # Database
                # ===========================================
                DB_USER=%s
                DB_PASS=%s
                DB_NAME=%s
                DB_PORT=5432

                # ===========================================
                # Application
                # ===========================================
                APP_PORT=8080

                # ===========================================
                # Redis (optional - use with: docker compose --profile cache up)
                # ===========================================
                REDIS_PORT=6379

                # ===========================================
                # MailHog (optional - use with: docker compose --profile mail up)
                # ===========================================
                MAILHOG_SMTP=1025
                MAILHOG_UI=8025

                # ===========================================
                # pgAdmin (optional - use with: docker compose --profile admin up)
                # ===========================================
                PGADMIN_PORT=5050
                PGADMIN_EMAIL=admin@local.dev
                PGADMIN_PASSWORD=admin

                # ===========================================
                # Observability (optional - use with: docker compose --profile observability up)
                # ===========================================
                PROMETHEUS_PORT=9090
                GRAFANA_PORT=3000
                GRAFANA_USER=admin
                GRAFANA_PASSWORD=admin
                """
                .formatted(dbUser, dbPassword, dbName);
    }
}
