package com.jnzader.apigen.codegen.generator.dx;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Generator for mise.toml task runner configuration.
 *
 * <p>mise is a polyglot task runner that provides unified commands across all languages. This
 * generator creates language-specific mise.toml files with common tasks like dev, test, lint, fmt,
 * build, docker, etc.
 *
 * @see <a href="https://mise.jdx.dev/">mise documentation</a>
 */
public class MiseGenerator {

    private final String projectName;
    private final String dbUser;
    private final String dbName;

    public MiseGenerator(String projectName, String dbUser, String dbName) {
        this.projectName = projectName;
        this.dbUser = dbUser != null ? dbUser : "app";
        this.dbName = dbName != null ? dbName : "appdb";
    }

    /**
     * Generates mise.toml content for the specified language.
     *
     * @param language the target language/framework
     * @return map with file path as key and content as value
     */
    public Map<String, String> generate(DxLanguage language) {
        Map<String, String> files = new LinkedHashMap<>();
        String content =
                switch (language) {
                    case JAVA_SPRING, KOTLIN_SPRING -> generateJvmMise(language);
                    case CSHARP_ASPNET -> generateCSharpMise();
                    case PYTHON_FASTAPI -> generatePythonMise();
                    case TYPESCRIPT_NESTJS -> generateTypeScriptMise();
                    case PHP_LARAVEL -> generatePhpMise();
                    case GO_GIN, GO_CHI -> generateGoMise();
                    case RUST_AXUM -> generateRustMise();
                };
        files.put("mise.toml", content);
        return files;
    }

    private String generateJvmMise(DxLanguage language) {
        String langName = language == DxLanguage.KOTLIN_SPRING ? "kotlin" : "java";
        return """
        # mise.toml - Generated by APiGen
        # Task runner configuration for %s/%s
        # Docs: https://mise.jdx.dev/

        [tools]
        java = "%s"

        [env]
        JAVA_HOME = "{{env.MISE_JAVA_HOME}}"
        GRADLE_OPTS = "-Xmx512m -Dorg.gradle.daemon=false"

        [tasks.dev]
        description = "Start development server with hot reload"
        run = "./gradlew bootRun"

        [tasks.test]
        description = "Run all tests"
        run = "./gradlew test"

        [tasks.test-unit]
        description = "Run unit tests only"
        run = "./gradlew test --tests '*Test' -x integrationTest"

        [tasks.test-it]
        description = "Run integration tests only"
        run = "./gradlew integrationTest"

        [tasks.lint]
        description = "Check code formatting"
        run = "./gradlew spotlessCheck"

        [tasks.fmt]
        description = "Format all code"
        run = "./gradlew spotlessApply"

        [tasks.build]
        description = "Build production JAR"
        run = "./gradlew build -x test"

        [tasks.clean]
        description = "Clean build artifacts"
        run = "./gradlew clean"

        [tasks.deps]
        description = "Check for dependency updates"
        run = "./gradlew dependencyUpdates"

        [tasks.coverage]
        description = "Generate test coverage report"
        run = "./gradlew jacocoTestReport && echo 'Report: build/reports/jacoco/test/html/index.html'"

        [tasks.docker]
        description = "Build Docker image"
        run = "docker build -t %s:latest ."

        [tasks.up]
        description = "Start Docker services"
        run = "docker compose up -d"

        [tasks.down]
        description = "Stop Docker services"
        run = "docker compose down"

        [tasks.logs]
        description = "Tail application logs"
        run = "docker compose logs -f"

        [tasks.db]
        description = "Connect to PostgreSQL"
        run = "docker compose exec postgres psql -U %s -d %s"

        [tasks.migrate]
        description = "Run Flyway migrations"
        run = "./gradlew flywayMigrate"

        [tasks.migrate-info]
        description = "Show migration status"
        run = "./gradlew flywayInfo"
        """
                .formatted(
                        langName,
                        language.getFramework(),
                        language.getLanguageVersion(),
                        projectName,
                        dbUser,
                        dbName);
    }

    private String generateCSharpMise() {
        return """
        # mise.toml - Generated by APiGen
        # Task runner configuration for C#/ASP.NET Core
        # Docs: https://mise.jdx.dev/

        [tools]
        dotnet = "8.0"

        [env]
        DOTNET_CLI_TELEMETRY_OPTOUT = "1"
        ASPNETCORE_ENVIRONMENT = "Development"

        [tasks.dev]
        description = "Start development server with hot reload"
        run = "dotnet watch run --project src/%s.Api"

        [tasks.test]
        description = "Run all tests"
        run = "dotnet test"

        [tasks.test-unit]
        description = "Run unit tests only"
        run = "dotnet test --filter Category=Unit"

        [tasks.test-it]
        description = "Run integration tests only"
        run = "dotnet test --filter Category=Integration"

        [tasks.lint]
        description = "Check code formatting"
        run = "dotnet format --verify-no-changes"

        [tasks.fmt]
        description = "Format all code"
        run = "dotnet format"

        [tasks.build]
        description = "Build release"
        run = "dotnet build -c Release"

        [tasks.publish]
        description = "Publish for deployment"
        run = "dotnet publish -c Release -o ./publish"

        [tasks.clean]
        description = "Clean build artifacts"
        run = "dotnet clean && rm -rf bin obj publish"

        [tasks.restore]
        description = "Restore NuGet packages"
        run = "dotnet restore"

        [tasks.docker]
        description = "Build Docker image"
        run = "docker build -t %s:latest ."

        [tasks.up]
        description = "Start Docker services"
        run = "docker compose up -d"

        [tasks.down]
        description = "Stop Docker services"
        run = "docker compose down"

        [tasks.ef-migrate]
        description = "Run EF Core migrations"
        run = "dotnet ef database update --project src/%s.Api"

        [tasks.ef-add]
        description = "Add new migration (usage: mise run ef-add MigrationName)"
        run = "dotnet ef migrations add $1 --project src/%s.Api"
        """
                .formatted(projectName, projectName, projectName, projectName);
    }

    private String generatePythonMise() {
        return """
        # mise.toml - Generated by APiGen
        # Task runner configuration for Python/FastAPI
        # Docs: https://mise.jdx.dev/

        [tools]
        python = "3.12"

        [env]
        PYTHONDONTWRITEBYTECODE = "1"
        PYTHONUNBUFFERED = "1"

        [tasks.dev]
        description = "Start development server with reload"
        run = "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"

        [tasks.test]
        description = "Run all tests"
        run = "pytest"

        [tasks.test-cov]
        description = "Run tests with coverage"
        run = "pytest --cov=app --cov-report=html && echo 'Report: htmlcov/index.html'"

        [tasks.lint]
        description = "Check code with ruff and mypy"
        run = "ruff check . && mypy app"

        [tasks.fmt]
        description = "Format code with ruff"
        run = "ruff format . && ruff check --fix ."

        [tasks.install]
        description = "Install dependencies"
        run = "pip install -e '.[dev]'"

        [tasks.freeze]
        description = "Export requirements"
        run = "pip freeze > requirements.txt"

        [tasks.docker]
        description = "Build Docker image"
        run = "docker build -t %s:latest ."

        [tasks.up]
        description = "Start Docker services"
        run = "docker compose up -d"

        [tasks.down]
        description = "Stop Docker services"
        run = "docker compose down"

        [tasks.shell]
        description = "Open Python shell with app context"
        run = "python -i -c 'from app.main import app'"

        [tasks.db]
        description = "Connect to PostgreSQL"
        run = "docker compose exec postgres psql -U %s -d %s"
        """
                .formatted(projectName, dbUser, dbName);
    }

    private String generateTypeScriptMise() {
        return """
        # mise.toml - Generated by APiGen
        # Task runner configuration for TypeScript/NestJS
        # Docs: https://mise.jdx.dev/

        [tools]
        node = "20"

        [env]
        NODE_ENV = "development"

        [tasks.dev]
        description = "Start development server with watch"
        run = "npm run start:dev"

        [tasks.test]
        description = "Run all tests"
        run = "npm test"

        [tasks.test-e2e]
        description = "Run e2e tests"
        run = "npm run test:e2e"

        [tasks.test-cov]
        description = "Run tests with coverage"
        run = "npm run test:cov"

        [tasks.lint]
        description = "Check code with Biome"
        run = "npx biome check ."

        [tasks.fmt]
        description = "Format code with Biome"
        run = "npx biome check --write ."

        [tasks.build]
        description = "Build for production"
        run = "npm run build"

        [tasks.install]
        description = "Install dependencies"
        run = "npm ci"

        [tasks.typecheck]
        description = "Run TypeScript type checking"
        run = "npx tsc --noEmit"

        [tasks.docker]
        description = "Build Docker image"
        run = "docker build -t %s:latest ."

        [tasks.up]
        description = "Start Docker services"
        run = "docker compose up -d"

        [tasks.down]
        description = "Stop Docker services"
        run = "docker compose down"

        [tasks.db]
        description = "Connect to PostgreSQL"
        run = "docker compose exec postgres psql -U %s -d %s"
        """
                .formatted(projectName, dbUser, dbName);
    }

    private String generatePhpMise() {
        return """
        # mise.toml - Generated by APiGen
        # Task runner configuration for PHP/Laravel
        # Docs: https://mise.jdx.dev/

        [tools]
        php = "8.4"
        node = "20"

        [env]
        APP_ENV = "local"

        [tasks.dev]
        description = "Start development server"
        run = "php artisan serve"

        [tasks.test]
        description = "Run all tests"
        run = "php artisan test"

        [tasks.test-cov]
        description = "Run tests with coverage"
        run = "php artisan test --coverage"

        [tasks.lint]
        description = "Check code style"
        run = "vendor/bin/pint --test"

        [tasks.fmt]
        description = "Format code"
        run = "vendor/bin/pint"

        [tasks.analyze]
        description = "Run static analysis"
        run = "vendor/bin/phpstan analyse"

        [tasks.install]
        description = "Install dependencies"
        run = "composer install"

        [tasks.docker]
        description = "Build Docker image"
        run = "docker build -t %s:latest ."

        [tasks.up]
        description = "Start Docker services"
        run = "docker compose up -d"

        [tasks.down]
        description = "Stop Docker services"
        run = "docker compose down"

        [tasks.artisan]
        description = "Run artisan command"
        run = "php artisan"

        [tasks.migrate]
        description = "Run migrations"
        run = "php artisan migrate"

        [tasks.seed]
        description = "Run seeders"
        run = "php artisan db:seed"

        [tasks.tinker]
        description = "Open Tinker REPL"
        run = "php artisan tinker"

        [tasks.db]
        description = "Connect to PostgreSQL"
        run = "docker compose exec postgres psql -U %s -d %s"
        """
                .formatted(projectName, dbUser, dbName);
    }

    private String generateGoMise() {
        return """
        # mise.toml - Generated by APiGen
        # Task runner configuration for Go
        # Docs: https://mise.jdx.dev/

        [tools]
        go = "1.23"

        [env]
        CGO_ENABLED = "0"
        GOPROXY = "https://proxy.golang.org,direct"

        [tasks.dev]
        description = "Start development server with hot reload"
        run = "air"

        [tasks.test]
        description = "Run all tests"
        run = "go test -v -race ./..."

        [tasks.test-cov]
        description = "Run tests with coverage"
        run = "go test -coverprofile=coverage.out ./... && go tool cover -html=coverage.out -o coverage.html && echo 'Report: coverage.html'"

        [tasks.lint]
        description = "Run linters"
        run = "golangci-lint run"

        [tasks.fmt]
        description = "Format code"
        run = "gofmt -w . && goimports -w ."

        [tasks.build]
        description = "Build binary"
        run = "go build -ldflags='-s -w' -o bin/%s ./cmd/server"

        [tasks.clean]
        description = "Clean build artifacts"
        run = "rm -rf bin/ coverage.out coverage.html"

        [tasks.mod-tidy]
        description = "Tidy go modules"
        run = "go mod tidy"

        [tasks.mod-verify]
        description = "Verify dependencies"
        run = "go mod verify"

        [tasks.vet]
        description = "Run go vet"
        run = "go vet ./..."

        [tasks.generate]
        description = "Run go generate"
        run = "go generate ./..."

        [tasks.docker]
        description = "Build Docker image"
        run = "docker build -t %s:latest ."

        [tasks.up]
        description = "Start Docker services"
        run = "docker compose up -d"

        [tasks.down]
        description = "Stop Docker services"
        run = "docker compose down"

        [tasks.db]
        description = "Connect to PostgreSQL"
        run = "docker compose exec postgres psql -U %s -d %s"
        """
                .formatted(projectName, projectName, dbUser, dbName);
    }

    private String generateRustMise() {
        return """
        # mise.toml - Generated by APiGen
        # Task runner configuration for Rust/Axum
        # Docs: https://mise.jdx.dev/

        [tools]
        rust = "1.85"

        [env]
        RUST_BACKTRACE = "1"
        RUST_LOG = "debug"

        [tasks.dev]
        description = "Start development server with watch"
        run = "cargo watch -x run"

        [tasks.test]
        description = "Run all tests"
        run = "cargo test"

        [tasks.test-verbose]
        description = "Run tests with output"
        run = "cargo test -- --nocapture"

        [tasks.lint]
        description = "Run clippy"
        run = "cargo clippy -- -D warnings"

        [tasks.fmt]
        description = "Format code"
        run = "cargo fmt"

        [tasks.fmt-check]
        description = "Check formatting"
        run = "cargo fmt --check"

        [tasks.build]
        description = "Build release"
        run = "cargo build --release"

        [tasks.clean]
        description = "Clean build artifacts"
        run = "cargo clean"

        [tasks.doc]
        description = "Generate documentation"
        run = "cargo doc --open"

        [tasks.audit]
        description = "Audit dependencies for vulnerabilities"
        run = "cargo audit"

        [tasks.bench]
        description = "Run benchmarks"
        run = "cargo bench"

        [tasks.docker]
        description = "Build Docker image"
        run = "docker build -t %s:latest ."

        [tasks.up]
        description = "Start Docker services"
        run = "docker compose up -d"

        [tasks.down]
        description = "Stop Docker services"
        run = "docker compose down"

        [tasks.db]
        description = "Connect to PostgreSQL"
        run = "docker compose exec postgres psql -U %s -d %s"
        """
                .formatted(projectName, dbUser, dbName);
    }
}
