package com.jnzader.apigen.codegen.generator.dx;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Generator for pre-commit hooks configuration.
 *
 * <p>pre-commit is a framework for managing git pre-commit hooks. This generator creates
 * language-specific .pre-commit-config.yaml files with hooks for:
 *
 * <ul>
 *   <li>Code formatting
 *   <li>Linting
 *   <li>Conventional commits enforcement
 *   <li>Secret detection
 *   <li>General file checks
 * </ul>
 *
 * @see <a href="https://pre-commit.com/">pre-commit documentation</a>
 */
public class PreCommitGenerator {

    /**
     * Generates .pre-commit-config.yaml content for the specified language.
     *
     * @param language the target language/framework
     * @return map with file path as key and content as value
     */
    public Map<String, String> generate(DxLanguage language) {
        Map<String, String> files = new LinkedHashMap<>();
        String content =
                switch (language) {
                    case JAVA_SPRING, KOTLIN_SPRING -> generateJvmPreCommit();
                    case CSHARP_ASPNET -> generateCSharpPreCommit();
                    case PYTHON_FASTAPI -> generatePythonPreCommit();
                    case TYPESCRIPT_NESTJS -> generateTypeScriptPreCommit();
                    case PHP_LARAVEL -> generatePhpPreCommit();
                    case GO_GIN, GO_CHI -> generateGoPreCommit();
                    case RUST_AXUM -> generateRustPreCommit();
                };
        files.put(".pre-commit-config.yaml", content);
        files.put(".secrets.baseline", generateSecretsBaseline());
        return files;
    }

    private String generateJvmPreCommit() {
        return """
        # .pre-commit-config.yaml - Generated by APiGen
        # Pre-commit hooks for Java/Kotlin Spring Boot
        # Docs: https://pre-commit.com/

        repos:
          # Language-specific formatting
          - repo: local
            hooks:
              - id: spotless-check
                name: Spotless Check
                entry: ./gradlew spotlessCheck
                language: system
                pass_filenames: false
                stages: [pre-commit]

          # Conventional commits enforcement
          - repo: https://github.com/compilerla/conventional-pre-commit
            rev: v3.4.0
            hooks:
              - id: conventional-pre-commit
                stages: [commit-msg]
                args: [--strict]

          # General file checks
          - repo: https://github.com/pre-commit/pre-commit-hooks
            rev: v4.6.0
            hooks:
              - id: trailing-whitespace
                args: [--markdown-linebreak-ext=md]
              - id: end-of-file-fixer
              - id: check-yaml
                args: [--unsafe]
              - id: check-json
              - id: check-toml
              - id: check-merge-conflict
              - id: detect-private-key
              - id: no-commit-to-branch
                args: [--branch, main, --branch, master]

          # Secrets detection
          - repo: https://github.com/Yelp/detect-secrets
            rev: v1.5.0
            hooks:
              - id: detect-secrets
                args: [--baseline, .secrets.baseline]
                exclude: package-lock.json|pnpm-lock.yaml|gradle.lockfile
        """;
    }

    private String generateCSharpPreCommit() {
        return """
        # .pre-commit-config.yaml - Generated by APiGen
        # Pre-commit hooks for C#/ASP.NET Core
        # Docs: https://pre-commit.com/

        repos:
          # Language-specific formatting
          - repo: local
            hooks:
              - id: dotnet-format
                name: dotnet format
                entry: dotnet format --verify-no-changes
                language: system
                pass_filenames: false
                stages: [pre-commit]

          # Conventional commits enforcement
          - repo: https://github.com/compilerla/conventional-pre-commit
            rev: v3.4.0
            hooks:
              - id: conventional-pre-commit
                stages: [commit-msg]
                args: [--strict]

          # General file checks
          - repo: https://github.com/pre-commit/pre-commit-hooks
            rev: v4.6.0
            hooks:
              - id: trailing-whitespace
                args: [--markdown-linebreak-ext=md]
              - id: end-of-file-fixer
              - id: check-yaml
              - id: check-json
              - id: check-merge-conflict
              - id: detect-private-key
              - id: no-commit-to-branch
                args: [--branch, main, --branch, master]

          # Secrets detection
          - repo: https://github.com/Yelp/detect-secrets
            rev: v1.5.0
            hooks:
              - id: detect-secrets
                args: [--baseline, .secrets.baseline]
        """;
    }

    private String generatePythonPreCommit() {
        return """
        # .pre-commit-config.yaml - Generated by APiGen
        # Pre-commit hooks for Python/FastAPI
        # Docs: https://pre-commit.com/

        repos:
          # Ruff - Fast Python linter and formatter
          - repo: https://github.com/astral-sh/ruff-pre-commit
            rev: v0.8.0
            hooks:
              - id: ruff
                args: [--fix]
              - id: ruff-format

          # Type checking with mypy
          - repo: https://github.com/pre-commit/mirrors-mypy
            rev: v1.13.0
            hooks:
              - id: mypy
                additional_dependencies: [types-all]
                args: [--ignore-missing-imports]

          # Conventional commits enforcement
          - repo: https://github.com/compilerla/conventional-pre-commit
            rev: v3.4.0
            hooks:
              - id: conventional-pre-commit
                stages: [commit-msg]
                args: [--strict]

          # General file checks
          - repo: https://github.com/pre-commit/pre-commit-hooks
            rev: v4.6.0
            hooks:
              - id: trailing-whitespace
                args: [--markdown-linebreak-ext=md]
              - id: end-of-file-fixer
              - id: check-yaml
              - id: check-toml
              - id: check-json
              - id: check-merge-conflict
              - id: detect-private-key
              - id: no-commit-to-branch
                args: [--branch, main, --branch, master]

          # Secrets detection
          - repo: https://github.com/Yelp/detect-secrets
            rev: v1.5.0
            hooks:
              - id: detect-secrets
                args: [--baseline, .secrets.baseline]
                exclude: poetry.lock
        """;
    }

    private String generateTypeScriptPreCommit() {
        return """
        # .pre-commit-config.yaml - Generated by APiGen
        # Pre-commit hooks for TypeScript/NestJS
        # Docs: https://pre-commit.com/

        repos:
          # Language-specific hooks
          - repo: local
            hooks:
              - id: biome
                name: Biome Check
                entry: npx biome check --write
                language: system
                types_or: [javascript, jsx, typescript, tsx, json]

              - id: typecheck
                name: TypeScript Check
                entry: npx tsc --noEmit
                language: system
                pass_filenames: false

          # Conventional commits enforcement
          - repo: https://github.com/compilerla/conventional-pre-commit
            rev: v3.4.0
            hooks:
              - id: conventional-pre-commit
                stages: [commit-msg]
                args: [--strict]

          # General file checks
          - repo: https://github.com/pre-commit/pre-commit-hooks
            rev: v4.6.0
            hooks:
              - id: trailing-whitespace
                args: [--markdown-linebreak-ext=md]
              - id: end-of-file-fixer
              - id: check-yaml
              - id: check-json
              - id: check-merge-conflict
              - id: detect-private-key
              - id: no-commit-to-branch
                args: [--branch, main, --branch, master]

          # Secrets detection
          - repo: https://github.com/Yelp/detect-secrets
            rev: v1.5.0
            hooks:
              - id: detect-secrets
                args: [--baseline, .secrets.baseline]
                exclude: package-lock.json|pnpm-lock.yaml
        """;
    }

    private String generatePhpPreCommit() {
        return """
        # .pre-commit-config.yaml - Generated by APiGen
        # Pre-commit hooks for PHP/Laravel
        # Docs: https://pre-commit.com/

        repos:
          # Language-specific hooks
          - repo: local
            hooks:
              - id: pint
                name: Laravel Pint
                entry: vendor/bin/pint --test
                language: system
                types: [php]

              - id: phpstan
                name: PHPStan
                entry: vendor/bin/phpstan analyse --memory-limit=512M
                language: system
                pass_filenames: false

          # Conventional commits enforcement
          - repo: https://github.com/compilerla/conventional-pre-commit
            rev: v3.4.0
            hooks:
              - id: conventional-pre-commit
                stages: [commit-msg]
                args: [--strict]

          # General file checks
          - repo: https://github.com/pre-commit/pre-commit-hooks
            rev: v4.6.0
            hooks:
              - id: trailing-whitespace
                args: [--markdown-linebreak-ext=md]
              - id: end-of-file-fixer
              - id: check-yaml
              - id: check-json
              - id: check-merge-conflict
              - id: detect-private-key
              - id: no-commit-to-branch
                args: [--branch, main, --branch, master]

          # Secrets detection
          - repo: https://github.com/Yelp/detect-secrets
            rev: v1.5.0
            hooks:
              - id: detect-secrets
                args: [--baseline, .secrets.baseline]
                exclude: composer.lock
        """;
    }

    private String generateGoPreCommit() {
        return """
        # .pre-commit-config.yaml - Generated by APiGen
        # Pre-commit hooks for Go
        # Docs: https://pre-commit.com/

        repos:
          # Language-specific hooks
          - repo: local
            hooks:
              - id: gofmt
                name: gofmt
                entry: gofmt -l -w
                language: system
                types: [go]

              - id: govet
                name: go vet
                entry: go vet ./...
                language: system
                pass_filenames: false

              - id: golangci-lint
                name: golangci-lint
                entry: golangci-lint run
                language: system
                pass_filenames: false

          # Conventional commits enforcement
          - repo: https://github.com/compilerla/conventional-pre-commit
            rev: v3.4.0
            hooks:
              - id: conventional-pre-commit
                stages: [commit-msg]
                args: [--strict]

          # General file checks
          - repo: https://github.com/pre-commit/pre-commit-hooks
            rev: v4.6.0
            hooks:
              - id: trailing-whitespace
                args: [--markdown-linebreak-ext=md]
              - id: end-of-file-fixer
              - id: check-yaml
              - id: check-json
              - id: check-merge-conflict
              - id: detect-private-key
              - id: no-commit-to-branch
                args: [--branch, main, --branch, master]

          # Secrets detection
          - repo: https://github.com/Yelp/detect-secrets
            rev: v1.5.0
            hooks:
              - id: detect-secrets
                args: [--baseline, .secrets.baseline]
                exclude: go.sum
        """;
    }

    private String generateRustPreCommit() {
        return """
        # .pre-commit-config.yaml - Generated by APiGen
        # Pre-commit hooks for Rust/Axum
        # Docs: https://pre-commit.com/

        repos:
          # Language-specific hooks
          - repo: local
            hooks:
              - id: cargo-fmt
                name: cargo fmt
                entry: cargo fmt --all -- --check
                language: system
                types: [rust]
                pass_filenames: false

              - id: cargo-clippy
                name: cargo clippy
                entry: cargo clippy --all-targets -- -D warnings
                language: system
                types: [rust]
                pass_filenames: false

              - id: cargo-test
                name: cargo test
                entry: cargo test
                language: system
                types: [rust]
                pass_filenames: false
                stages: [pre-push]

          # Conventional commits enforcement
          - repo: https://github.com/compilerla/conventional-pre-commit
            rev: v3.4.0
            hooks:
              - id: conventional-pre-commit
                stages: [commit-msg]
                args: [--strict]

          # General file checks
          - repo: https://github.com/pre-commit/pre-commit-hooks
            rev: v4.6.0
            hooks:
              - id: trailing-whitespace
                args: [--markdown-linebreak-ext=md]
              - id: end-of-file-fixer
              - id: check-yaml
              - id: check-toml
              - id: check-merge-conflict
              - id: detect-private-key
              - id: no-commit-to-branch
                args: [--branch, main, --branch, master]

          # Secrets detection
          - repo: https://github.com/Yelp/detect-secrets
            rev: v1.5.0
            hooks:
              - id: detect-secrets
                args: [--baseline, .secrets.baseline]
                exclude: Cargo.lock
        """;
    }

    private String generateSecretsBaseline() {
        return """
        {
          "version": "1.5.0",
          "plugins_used": [
            {"name": "ArtifactoryDetector"},
            {"name": "AWSKeyDetector"},
            {"name": "AzureStorageKeyDetector"},
            {"name": "BasicAuthDetector"},
            {"name": "CloudantDetector"},
            {"name": "DiscordBotTokenDetector"},
            {"name": "GitHubTokenDetector"},
            {"name": "GitLabTokenDetector"},
            {"name": "Base64HighEntropyString", "limit": 4.5},
            {"name": "HexHighEntropyString", "limit": 3.0},
            {"name": "IbmCloudIamDetector"},
            {"name": "IbmCosHmacDetector"},
            {"name": "IPPublicDetector"},
            {"name": "JwtTokenDetector"},
            {"name": "KeywordDetector", "keyword_exclude": ""},
            {"name": "MailchimpDetector"},
            {"name": "NpmDetector"},
            {"name": "OpenAIDetector"},
            {"name": "PrivateKeyDetector"},
            {"name": "PypiTokenDetector"},
            {"name": "SendGridDetector"},
            {"name": "SlackDetector"},
            {"name": "SoftlayerDetector"},
            {"name": "SquareOAuthDetector"},
            {"name": "StripeDetector"},
            {"name": "TelegramBotTokenDetector"},
            {"name": "TwilioKeyDetector"}
          ],
          "filters_used": [
            {"path": "detect_secrets.filters.allowlist.is_line_allowlisted"},
            {"path": "detect_secrets.filters.common.is_baseline_file", "filename": ".secrets.baseline"},
            {"path": "detect_secrets.filters.common.is_ignored_due_to_verification_policies", "min_level": 2},
            {"path": "detect_secrets.filters.heuristic.is_indirect_reference"},
            {"path": "detect_secrets.filters.heuristic.is_likely_id_string"},
            {"path": "detect_secrets.filters.heuristic.is_lock_file"},
            {"path": "detect_secrets.filters.heuristic.is_not_alphanumeric_string"},
            {"path": "detect_secrets.filters.heuristic.is_potential_uuid"},
            {"path": "detect_secrets.filters.heuristic.is_prefixed_with_dollar_sign"},
            {"path": "detect_secrets.filters.heuristic.is_sequential_string"},
            {"path": "detect_secrets.filters.heuristic.is_swagger_file"},
            {"path": "detect_secrets.filters.heuristic.is_templated_secret"}
          ],
          "results": {},
          "generated_at": "2026-01-25T00:00:00Z"
        }
        """;
    }
}
