package com.jnzader.apigen.codegen.generator.dx;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Generator for automated setup scripts.
 *
 * <p>Creates scripts/setup.sh (Unix) and scripts/setup.ps1 (Windows) that automate development
 * environment setup including:
 *
 * <ul>
 *   <li>Dependency verification
 *   <li>mise installation
 *   <li>Pre-commit hooks installation
 *   <li>Docker services startup
 *   <li>Database migrations
 * </ul>
 */
public class SetupScriptGenerator {

    private final String projectName;
    private final String dbUser;
    private final String dbName;
    private final String apigenVersion;

    public SetupScriptGenerator(
            String projectName, String dbUser, String dbName, String apigenVersion) {
        this.projectName = projectName;
        this.dbUser = dbUser != null ? dbUser : "app";
        this.dbName = dbName != null ? dbName : "appdb";
        this.apigenVersion = apigenVersion != null ? apigenVersion : "2.19.0";
    }

    /**
     * Generates setup scripts for the specified language.
     *
     * @param language the target language/framework
     * @return map with file paths as keys and content as values
     */
    public Map<String, String> generate(DxLanguage language) {
        Map<String, String> files = new LinkedHashMap<>();
        files.put("scripts/setup.sh", generateBashScript(language));
        files.put("scripts/setup.ps1", generatePowerShellScript(language));
        return files;
    }

    private String generateBashScript(DxLanguage language) {
        String langCheck = getLanguageCheck(language);
        String postSetup = getPostSetupCommands(language);

        return """
                #!/usr/bin/env bash
                # setup.sh - Generated by APiGen v%s
                # One-command development environment setup for %s

                set -euo pipefail

                # Colors
                RED='\\033[0;31m'
                GREEN='\\033[0;32m'
                YELLOW='\\033[1;33m'
                BLUE='\\033[0;34m'
                NC='\\033[0m' # No Color

                log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
                log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
                log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
                log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

                echo ""
                echo "================================================"
                echo "  %s - Development Setup"
                echo "  Generated by APiGen v%s"
                echo "================================================"
                echo ""

                # 1. Check required tools
                log_info "Checking required tools..."

                check_tool() {
                    if ! command -v "$1" &> /dev/null; then
                        log_error "$1 is not installed"
                        return 1
                    fi
                    log_success "$1 found: $(command -v "$1")"
                }

                check_tool docker || exit 1
                %s

                # Check Docker is running
                if ! docker info &> /dev/null; then
                    log_error "Docker is not running. Please start Docker Desktop."
                    exit 1
                fi
                log_success "Docker is running"

                # 2. Install mise (optional)
                if ! command -v mise &> /dev/null; then
                    log_warn "mise not found. Installing..."
                    curl https://mise.run | sh
                    eval "$(mise activate bash)"
                    log_success "mise installed"
                else
                    log_success "mise found"
                fi

                # 3. Install pre-commit (optional)
                if ! command -v pre-commit &> /dev/null; then
                    log_warn "pre-commit not found. Installing..."
                    pip install pre-commit 2>/dev/null || pip3 install pre-commit 2>/dev/null || {
                        log_warn "Could not install pre-commit. Git hooks will not be available."
                    }
                fi

                # 4. Setup git hooks
                if command -v pre-commit &> /dev/null; then
                    log_info "Installing git hooks..."
                    pre-commit install
                    pre-commit install --hook-type commit-msg
                    log_success "Git hooks installed"
                fi

                # 5. Start Docker services
                log_info "Starting Docker services..."
                docker compose up -d

                # 6. Wait for database
                log_info "Waiting for database to be ready..."
                RETRIES=30
                until docker compose exec -T postgres pg_isready -U %s -d %s 2>/dev/null || [ $RETRIES -eq 0 ]; do
                    echo -n "."
                    RETRIES=$((RETRIES-1))
                    sleep 1
                done
                echo ""

                if [ $RETRIES -eq 0 ]; then
                    log_error "Database did not become ready in time"
                    exit 1
                fi
                log_success "Database is ready"

                # 7. Post-setup commands (language-specific)
                %s

                # Done
                echo ""
                echo "================================================"
                echo -e "${GREEN}  Setup complete!${NC}"
                echo "================================================"
                echo ""
                echo "Quick start commands:"
                echo "  mise run dev     - Start development server"
                echo "  mise run test    - Run all tests"
                echo "  mise run lint    - Check code style"
                echo "  mise run up      - Start Docker services"
                echo ""
                echo "Documentation:"
                echo "  README.md        - Project overview"
                echo ""
                """
                .formatted(
                        apigenVersion,
                        projectName,
                        projectName,
                        apigenVersion,
                        langCheck,
                        dbUser,
                        dbName,
                        postSetup);
    }

    private String generatePowerShellScript(DxLanguage language) {
        String langCheck = getLanguageCheckPowerShell(language);
        String postSetup = getPostSetupCommandsPowerShell(language);

        return """
                # setup.ps1 - Generated by APiGen v%s
                # Windows development environment setup for %s

                $ErrorActionPreference = "Stop"

                function Write-Info { param($msg) Write-Host "[INFO] $msg" -ForegroundColor Blue }
                function Write-Ok { param($msg) Write-Host "[OK] $msg" -ForegroundColor Green }
                function Write-Warn { param($msg) Write-Host "[WARN] $msg" -ForegroundColor Yellow }
                function Write-Err { param($msg) Write-Host "[ERROR] $msg" -ForegroundColor Red }

                Write-Host ""
                Write-Host "================================================" -ForegroundColor Cyan
                Write-Host "  %s - Development Setup"
                Write-Host "  Generated by APiGen v%s"
                Write-Host "================================================" -ForegroundColor Cyan
                Write-Host ""

                # 1. Check Docker
                Write-Info "Checking required tools..."

                if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
                    Write-Err "Docker is not installed"
                    exit 1
                }
                Write-Ok "Docker found"

                # Check Docker is running
                $dockerInfo = docker info 2>&1
                if ($LASTEXITCODE -ne 0) {
                    Write-Err "Docker is not running. Please start Docker Desktop."
                    exit 1
                }
                Write-Ok "Docker is running"

                # Check language-specific tools
                %s

                # 2. Install mise if not present
                if (-not (Get-Command mise -ErrorAction SilentlyContinue)) {
                    Write-Warn "mise not found. Installing..."
                    try {
                        irm https://mise.run | iex
                        Write-Ok "mise installed"
                    } catch {
                        Write-Warn "Could not install mise automatically. Visit https://mise.jdx.dev/"
                    }
                } else {
                    Write-Ok "mise found"
                }

                # 3. Install pre-commit if not present
                if (-not (Get-Command pre-commit -ErrorAction SilentlyContinue)) {
                    Write-Warn "pre-commit not found. Installing..."
                    try {
                        pip install pre-commit
                        Write-Ok "pre-commit installed"
                    } catch {
                        Write-Warn "Could not install pre-commit. Git hooks will not be available."
                    }
                }

                # 4. Setup git hooks
                if (Get-Command pre-commit -ErrorAction SilentlyContinue) {
                    Write-Info "Installing git hooks..."
                    pre-commit install
                    pre-commit install --hook-type commit-msg
                    Write-Ok "Git hooks installed"
                }

                # 5. Start Docker services
                Write-Info "Starting Docker services..."
                docker compose up -d

                # 6. Wait for database
                Write-Info "Waiting for database..."
                $retries = 30
                while ($retries -gt 0) {
                    $result = docker compose exec -T postgres pg_isready -U %s -d %s 2>&1
                    if ($LASTEXITCODE -eq 0) { break }
                    Write-Host "." -NoNewline
                    Start-Sleep -Seconds 1
                    $retries--
                }
                Write-Host ""

                if ($retries -eq 0) {
                    Write-Err "Database did not become ready in time"
                    exit 1
                }
                Write-Ok "Database is ready"

                # 7. Post-setup commands
                %s

                # Done
                Write-Host ""
                Write-Host "================================================" -ForegroundColor Cyan
                Write-Ok "Setup complete!"
                Write-Host "================================================" -ForegroundColor Cyan
                Write-Host ""
                Write-Host "Commands: mise run dev | mise run test | mise run lint"
                """
                .formatted(
                        apigenVersion,
                        projectName,
                        projectName,
                        apigenVersion,
                        langCheck,
                        dbUser,
                        dbName,
                        postSetup);
    }

    private String getLanguageCheck(DxLanguage language) {
        return switch (language) {
            case JAVA_SPRING, KOTLIN_SPRING -> "check_tool java || exit 1";
            case CSHARP_ASPNET -> "check_tool dotnet || exit 1";
            case PYTHON_FASTAPI -> "check_tool python || check_tool python3 || exit 1";
            case TYPESCRIPT_NESTJS -> "check_tool node || exit 1\ncheck_tool npm || exit 1";
            case PHP_LARAVEL -> "check_tool php || exit 1\ncheck_tool composer || exit 1";
            case GO_GIN, GO_CHI -> "check_tool go || exit 1";
            case RUST_AXUM -> "check_tool cargo || exit 1";
        };
    }

    private String getLanguageCheckPowerShell(DxLanguage language) {
        return switch (language) {
            case JAVA_SPRING, KOTLIN_SPRING -> """
                    if (-not (Get-Command java -ErrorAction SilentlyContinue)) {
                        Write-Err "Java is not installed"
                        exit 1
                    }
                    Write-Ok "Java found"
                    """;
            case CSHARP_ASPNET -> """
                    if (-not (Get-Command dotnet -ErrorAction SilentlyContinue)) {
                        Write-Err ".NET SDK is not installed"
                        exit 1
                    }
                    Write-Ok ".NET SDK found"
                    """;
            case PYTHON_FASTAPI -> """
                    if (-not (Get-Command python -ErrorAction SilentlyContinue)) {
                        Write-Err "Python is not installed"
                        exit 1
                    }
                    Write-Ok "Python found"
                    """;
            case TYPESCRIPT_NESTJS -> """
                    if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
                        Write-Err "Node.js is not installed"
                        exit 1
                    }
                    Write-Ok "Node.js found"
                    """;
            case PHP_LARAVEL -> """
                    if (-not (Get-Command php -ErrorAction SilentlyContinue)) {
                        Write-Err "PHP is not installed"
                        exit 1
                    }
                    Write-Ok "PHP found"
                    """;
            case GO_GIN, GO_CHI -> """
                    if (-not (Get-Command go -ErrorAction SilentlyContinue)) {
                        Write-Err "Go is not installed"
                        exit 1
                    }
                    Write-Ok "Go found"
                    """;
            case RUST_AXUM -> """
                    if (-not (Get-Command cargo -ErrorAction SilentlyContinue)) {
                        Write-Err "Rust/Cargo is not installed"
                        exit 1
                    }
                    Write-Ok "Rust found"
                    """;
        };
    }

    private String getPostSetupCommands(DxLanguage language) {
        return switch (language) {
            case JAVA_SPRING, KOTLIN_SPRING -> """
                    log_info "Running database migrations..."
                    ./gradlew flywayMigrate --quiet
                    log_success "Migrations complete"

                    log_info "Verifying project builds..."
                    ./gradlew classes --quiet
                    log_success "Project compiles successfully"
                    """;
            case CSHARP_ASPNET -> """
                    log_info "Restoring NuGet packages..."
                    dotnet restore
                    log_success "Packages restored"

                    log_info "Running EF Core migrations..."
                    dotnet ef database update --project src/*.Api || log_warn "EF migrations skipped"
                    """;
            case PYTHON_FASTAPI -> """
                    log_info "Installing Python dependencies..."
                    pip install -e '.[dev]' || pip3 install -e '.[dev]'
                    log_success "Dependencies installed"
                    """;
            case TYPESCRIPT_NESTJS -> """
                    log_info "Installing npm dependencies..."
                    npm ci
                    log_success "Dependencies installed"
                    """;
            case PHP_LARAVEL -> """
                    log_info "Installing Composer dependencies..."
                    composer install
                    log_success "Dependencies installed"

                    log_info "Running Laravel migrations..."
                    php artisan migrate --force || log_warn "Migrations skipped"
                    """;
            case GO_GIN, GO_CHI -> """
                    log_info "Downloading Go modules..."
                    go mod download
                    log_success "Modules downloaded"
                    """;
            case RUST_AXUM -> """
                    log_info "Building Rust project..."
                    cargo build
                    log_success "Build successful"
                    """;
        };
    }

    private String getPostSetupCommandsPowerShell(DxLanguage language) {
        return switch (language) {
            case JAVA_SPRING, KOTLIN_SPRING -> """
                    Write-Info "Running database migrations..."
                    .\\gradlew.bat flywayMigrate --quiet
                    Write-Ok "Migrations complete"
                    """;
            case CSHARP_ASPNET -> """
                    Write-Info "Restoring NuGet packages..."
                    dotnet restore
                    Write-Ok "Packages restored"
                    """;
            case PYTHON_FASTAPI -> """
                    Write-Info "Installing Python dependencies..."
                    pip install -e ".[dev]"
                    Write-Ok "Dependencies installed"
                    """;
            case TYPESCRIPT_NESTJS -> """
                    Write-Info "Installing npm dependencies..."
                    npm ci
                    Write-Ok "Dependencies installed"
                    """;
            case PHP_LARAVEL -> """
                    Write-Info "Installing Composer dependencies..."
                    composer install
                    Write-Ok "Dependencies installed"
                    """;
            case GO_GIN, GO_CHI -> """
                    Write-Info "Downloading Go modules..."
                    go mod download
                    Write-Ok "Modules downloaded"
                    """;
            case RUST_AXUM -> """
                    Write-Info "Building Rust project..."
                    cargo build
                    Write-Ok "Build successful"
                    """;
        };
    }
}
