package com.jnzader.apigen.codegen.generator.typescript.config;

import com.jnzader.apigen.codegen.generator.api.Feature;
import com.jnzader.apigen.codegen.generator.api.ProjectConfig;
import com.jnzader.apigen.codegen.generator.typescript.TypeScriptTypeMapper;
import com.jnzader.apigen.codegen.model.SqlSchema;
import com.jnzader.apigen.codegen.model.SqlTable;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Generates configuration files for NestJS projects.
 *
 * <p>Generates:
 *
 * <ul>
 *   <li>package.json
 *   <li>tsconfig.json
 *   <li>nest-cli.json
 *   <li>.env.example
 *   <li>Dockerfile
 *   <li>docker-compose.yml
 *   <li>README.md
 *   <li>.gitignore
 * </ul>
 */
public class TypeScriptConfigGenerator {

    private final String projectName;
    private final TypeScriptTypeMapper typeMapper;

    public TypeScriptConfigGenerator(String projectName) {
        this.projectName = projectName;
        this.typeMapper = new TypeScriptTypeMapper();
    }

    /**
     * Generates all configuration files.
     *
     * @param schema the SQL schema
     * @param config the project configuration
     * @return map of file paths to content
     */
    public Map<String, String> generate(SqlSchema schema, ProjectConfig config) {
        Map<String, String> files = new LinkedHashMap<>();

        files.put("package.json", generatePackageJson());
        files.put("tsconfig.json", generateTsConfig());
        files.put("tsconfig.build.json", generateTsBuildConfig());
        files.put("nest-cli.json", generateNestCliJson());
        files.put(".env.example", generateEnvExample());
        files.put(".env", generateEnvExample());
        files.put(".gitignore", generateGitignore());
        files.put("README.md", generateReadme(schema));
        files.put(".prettierrc", generatePrettierRc());
        files.put(".eslintrc.js", generateEslintRc());

        if (config.isFeatureEnabled(Feature.DOCKER)) {
            files.put("Dockerfile", generateDockerfile());
            files.put("docker-compose.yml", generateDockerCompose());
            files.put(".dockerignore", generateDockerignore());
        }

        return files;
    }

    private String generatePackageJson() {
        String kebabName = typeMapper.toKebabCase(projectName);
        return """
        {
          "name": "%s",
          "version": "1.0.0",
          "description": "REST API generated by APiGen",
          "author": "",
          "private": true,
          "license": "MIT",
          "scripts": {
            "build": "nest build",
            "format": "prettier --write \\"src/**/*.ts\\" \\"test/**/*.ts\\"",
            "start": "nest start",
            "start:dev": "nest start --watch",
            "start:debug": "nest start --debug --watch",
            "start:prod": "node dist/main",
            "lint": "eslint \\"{src,apps,libs,test}/**/*.ts\\" --fix",
            "test": "jest",
            "test:watch": "jest --watch",
            "test:cov": "jest --coverage",
            "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
            "test:e2e": "jest --config ./test/jest-e2e.json",
            "typeorm": "ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js",
            "migration:generate": "npm run typeorm -- migration:generate -d src/config/data-source.ts",
            "migration:run": "npm run typeorm -- migration:run -d src/config/data-source.ts",
            "migration:revert": "npm run typeorm -- migration:revert -d src/config/data-source.ts"
          },
          "dependencies": {
            "@nestjs/common": "^11.1.0",
            "@nestjs/config": "^4.0.0",
            "@nestjs/core": "^11.1.0",
            "@nestjs/platform-express": "^11.1.0",
            "@nestjs/swagger": "^11.1.0",
            "@nestjs/typeorm": "^11.0.0",
            "class-transformer": "^0.5.1",
            "class-validator": "^0.14.1",
            "pg": "^8.12.0",
            "reflect-metadata": "^0.2.2",
            "rxjs": "^7.8.1",
            "typeorm": "^0.3.20"
          },
          "devDependencies": {
            "@nestjs/cli": "^11.0.0",
            "@nestjs/schematics": "^11.0.0",
            "@nestjs/testing": "^11.1.0",
            "@types/express": "^4.17.21",
            "@types/jest": "^29.5.12",
            "@types/node": "^22.0.0",
            "@typescript-eslint/eslint-plugin": "^7.0.0",
            "@typescript-eslint/parser": "^7.0.0",
            "eslint": "^8.57.0",
            "eslint-config-prettier": "^9.1.0",
            "eslint-plugin-prettier": "^5.2.0",
            "jest": "^29.7.0",
            "prettier": "^3.3.0",
            "source-map-support": "^0.5.21",
            "supertest": "^7.0.0",
            "ts-jest": "^29.2.0",
            "ts-loader": "^9.5.0",
            "ts-node": "^10.9.2",
            "tsconfig-paths": "^4.2.0",
            "typescript": "^5.9.0"
          },
          "jest": {
            "moduleFileExtensions": ["js", "json", "ts"],
            "rootDir": "src",
            "testRegex": ".*\\\\.spec\\\\.ts$",
            "transform": {
              "^.+\\\\.(t|j)s$": "ts-jest"
            },
            "collectCoverageFrom": ["**/*.(t|j)s"],
            "coverageDirectory": "../coverage",
            "testEnvironment": "node"
          }
        }
        """
                .formatted(kebabName);
    }

    private String generateTsConfig() {
        return """
        {
          "compilerOptions": {
            "module": "commonjs",
            "declaration": true,
            "removeComments": true,
            "emitDecoratorMetadata": true,
            "experimentalDecorators": true,
            "allowSyntheticDefaultImports": true,
            "target": "ES2022",
            "sourceMap": true,
            "outDir": "./dist",
            "baseUrl": "./",
            "incremental": true,
            "skipLibCheck": true,
            "strictNullChecks": true,
            "noImplicitAny": true,
            "strictBindCallApply": true,
            "forceConsistentCasingInFileNames": true,
            "noFallthroughCasesInSwitch": true,
            "esModuleInterop": true,
            "resolveJsonModule": true
          }
        }
        """;
    }

    private String generateTsBuildConfig() {
        return """
        {
          "extends": "./tsconfig.json",
          "exclude": ["node_modules", "test", "dist", "**/*spec.ts"]
        }
        """;
    }

    private String generateNestCliJson() {
        return """
        {
          "$schema": "https://json.schemastore.org/nest-cli",
          "collection": "@nestjs/schematics",
          "sourceRoot": "src",
          "compilerOptions": {
            "deleteOutDir": true
          }
        }
        """;
    }

    private String generateEnvExample() {
        String snakeName =
                projectName
                        .replaceAll("([a-z])([A-Z])", "$1_$2")
                        .replaceAll("-", "_")
                        .toLowerCase();
        return """
        # Application
        NODE_ENV=development
        PORT=3000

        # Database
        DB_HOST=localhost
        DB_PORT=5432
        DB_USERNAME=postgres
        DB_PASSWORD=postgres
        DB_DATABASE=%s

        # JWT (optional)
        JWT_SECRET=your-secret-key
        JWT_EXPIRATION=3600
        """
                .formatted(snakeName);
    }

    private String generateGitignore() {
        return """
        # Dependencies
        node_modules/

        # Build output
        dist/
        build/

        # Environment files
        .env
        .env.local
        .env.*.local

        # IDE
        .idea/
        .vscode/
        *.swp
        *.swo

        # Logs
        logs/
        *.log
        npm-debug.log*

        # Coverage
        coverage/

        # OS
        .DS_Store
        Thumbs.db

        # Test
        .nyc_output/
        """;
    }

    private String generateReadme(SqlSchema schema) {
        StringBuilder sb = new StringBuilder();
        String kebabName = typeMapper.toKebabCase(projectName);

        sb.append("# ").append(projectName).append("\n\n");
        sb.append("REST API generated by APiGen using NestJS and TypeORM.\n\n");

        sb.append("## Requirements\n\n");
        sb.append("- Node.js 20+\n");
        sb.append("- PostgreSQL 15+\n");
        sb.append("- npm or yarn\n\n");

        sb.append("## Getting Started\n\n");
        sb.append("### 1. Install dependencies\n\n");
        sb.append("```bash\n");
        sb.append("npm install\n");
        sb.append("```\n\n");

        sb.append("### 2. Configure environment\n\n");
        sb.append("```bash\n");
        sb.append("cp .env.example .env\n");
        sb.append("# Edit .env with your database credentials\n");
        sb.append("```\n\n");

        sb.append("### 3. Create database\n\n");
        sb.append("```bash\n");
        sb.append("createdb ").append(kebabName).append("\n");
        sb.append("```\n\n");

        sb.append("### 4. Run the application\n\n");
        sb.append("```bash\n");
        sb.append("# Development\n");
        sb.append("npm run start:dev\n\n");
        sb.append("# Production\n");
        sb.append("npm run build\n");
        sb.append("npm run start:prod\n");
        sb.append("```\n\n");

        sb.append("## API Documentation\n\n");
        sb.append("Once the application is running, visit:\n");
        sb.append("- Swagger UI: http://localhost:3000/api/docs\n\n");

        sb.append("## Available Endpoints\n\n");
        for (SqlTable table : schema.getEntityTables()) {
            String entityName = table.getEntityName();
            String pluralKebab = typeMapper.toKebabCase(typeMapper.pluralize(entityName));
            sb.append("### ").append(entityName).append("\n\n");
            sb.append("| Method | Endpoint | Description |\n");
            sb.append("|--------|----------|-------------|\n");
            sb.append("| GET | `/api/v1/")
                    .append(pluralKebab)
                    .append("` | List all with pagination |\n");
            sb.append("| GET | `/api/v1/").append(pluralKebab).append("/:id` | Get by ID |\n");
            sb.append("| POST | `/api/v1/").append(pluralKebab).append("` | Create new |\n");
            sb.append("| PUT | `/api/v1/").append(pluralKebab).append("/:id` | Update |\n");
            sb.append("| DELETE | `/api/v1/").append(pluralKebab).append("/:id` | Soft delete |\n");
            sb.append("| POST | `/api/v1/")
                    .append(pluralKebab)
                    .append("/:id/restore` | Restore deleted |\n\n");
        }

        sb.append("## Docker\n\n");
        sb.append("```bash\n");
        sb.append("# Build and run with Docker Compose\n");
        sb.append("docker-compose up -d\n");
        sb.append("```\n\n");

        sb.append("## Testing\n\n");
        sb.append("```bash\n");
        sb.append("# Unit tests\n");
        sb.append("npm run test\n\n");
        sb.append("# E2E tests\n");
        sb.append("npm run test:e2e\n\n");
        sb.append("# Test coverage\n");
        sb.append("npm run test:cov\n");
        sb.append("```\n\n");

        sb.append("## License\n\n");
        sb.append("MIT\n");

        return sb.toString();
    }

    private String generatePrettierRc() {
        return """
        {
          "singleQuote": true,
          "trailingComma": "all",
          "tabWidth": 2,
          "semi": true,
          "printWidth": 100
        }
        """;
    }

    private String generateEslintRc() {
        return """
        module.exports = {
          parser: '@typescript-eslint/parser',
          parserOptions: {
            project: 'tsconfig.json',
            tsconfigRootDir: __dirname,
            sourceType: 'module',
          },
          plugins: ['@typescript-eslint/eslint-plugin'],
          extends: [
            'plugin:@typescript-eslint/recommended',
            'plugin:prettier/recommended',
          ],
          root: true,
          env: {
            node: true,
            jest: true,
          },
          ignorePatterns: ['.eslintrc.js'],
          rules: {
            '@typescript-eslint/interface-name-prefix': 'off',
            '@typescript-eslint/explicit-function-return-type': 'off',
            '@typescript-eslint/explicit-module-boundary-types': 'off',
            '@typescript-eslint/no-explicit-any': 'off',
          },
        };
        """;
    }

    private String generateDockerfile() {
        return """
        # Build stage
        FROM node:20-alpine AS builder

        WORKDIR /app

        COPY package*.json ./
        RUN npm ci

        COPY . .
        RUN npm run build

        # Production stage
        FROM node:20-alpine

        WORKDIR /app

        COPY package*.json ./
        RUN npm ci --only=production

        COPY --from=builder /app/dist ./dist

        ENV NODE_ENV=production
        ENV PORT=3000

        EXPOSE 3000

        CMD ["node", "dist/main"]
        """;
    }

    private String generateDockerCompose() {
        String kebabName = typeMapper.toKebabCase(projectName);
        String snakeName =
                projectName
                        .replaceAll("([a-z])([A-Z])", "$1_$2")
                        .replaceAll("-", "_")
                        .toLowerCase();

        return """
        version: '3.8'

        services:
          app:
            build: .
            container_name: %s-api
            ports:
              - "3000:3000"
            environment:
              - NODE_ENV=production
              - DB_HOST=db
              - DB_PORT=5432
              - DB_USERNAME=postgres
              - DB_PASSWORD=postgres
              - DB_DATABASE=%s
            depends_on:
              db:
                condition: service_healthy
            restart: unless-stopped

          db:
            image: postgres:16-alpine
            container_name: %s-db
            environment:
              - POSTGRES_USER=postgres
              - POSTGRES_PASSWORD=postgres
              - POSTGRES_DB=%s
            volumes:
              - postgres_data:/var/lib/postgresql/data
            ports:
              - "5432:5432"
            healthcheck:
              test: ["CMD-SHELL", "pg_isready -U postgres"]
              interval: 10s
              timeout: 5s
              retries: 5
            restart: unless-stopped

        volumes:
          postgres_data:
        """
                .formatted(kebabName, snakeName, kebabName, snakeName);
    }

    private String generateDockerignore() {
        return """
        node_modules
        dist
        .git
        .gitignore
        .env
        .env.local
        *.md
        .idea
        .vscode
        coverage
        test
        """;
    }
}
